In [18]:

# import "array" for demonstrating array operation
import array
arr = array.array('I',[2,4,6,8,10,12])
print("Mee created array:",end="")
for I in range(0,5):
 print(arr[I],end=" ")
 print("\r")

Mee created array:2 
4 
6 
8 
10 


In [ ]:
import pandas as pd
dict = {'name':["Smith","Williom","Phill","Parker"],
'age':["28","39","34","36"]}
info = pd.DataFrame(dict,index=[True,True,False,True])
print(info)

In [ ]:
dict = {'name':["Smith","Williom","Phill","Parker"],
'age':["28","39","34","36"]}
info = pd.DataFrame(dict,index=[True,True,False,True])
print(info.loc[True])

In [17]:
import numpy as np
arr=np.arange(16)
print("The Original array is: \n",arr)
arr = np.arange(16).reshape(2,8)
print("\nreshapedarray.:\n",arr)
arr=np.arange(16).reshape(8,2)
print("\nreshaped array:\n",arr)

The Original array is: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshapedarray.:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

reshaped array:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
